# Generated by Django 4.1.1 on 2022-09-05 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_player_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 6, 1, 32, 58, 179037)),
        ),
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
